[build-system]
requires = ["setuptools>=68.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "rodski"
version = "6.7.0"
description = "RodSki 关键字驱动自动化测试框架"
requires-python = ">=3.8"

[tool.setuptools.packages.find]
include = ["rodski*"]
exclude = ["rodski.tests*", "rodski.docs*"]

[tool.black]
line-length = 120
target-version = ['py38']
exclude = '''
/(
    \.git
  | \.venv
  | venv
  | build
  | dist
)/
'''

[tool.isort]
profile = "black"
line_length = 120

[tool.coverage.run]
source = ["rodski"]
omit = ["*/tests/*", "*/demo_*/*"]

[tool.coverage.report]
fail_under = 80
precision = 2
